# Generated by Django 3.2.7 on 2022-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='working well!'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
