# Generated by Django 3.2.7 on 2022-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, default='unknown', max_length=200, null=True),
        ),
    ]
