# Generated by Django 3.2.7 on 2022-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_feedback_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(blank=True, default='no feedback'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(blank=True, default='unknown', max_length=200),
        ),
    ]
