# Generated by Django 3.2.7 on 2022-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Precaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=255)),
                ('Precaution_1', models.CharField(max_length=255)),
                ('Precaution_2', models.CharField(max_length=255)),
                ('Precaution_3', models.CharField(max_length=255)),
                ('Precaution_4', models.CharField(max_length=255)),
            ],
        ),
    ]
