# Generated by Django 3.2.7 on 2022-05-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_updateform_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='address',
            field=models.CharField(max_length=400),
        ),
    ]
